const REQUEST_API_DATA = 'REQUEST_API_DATA';
const RECEIVE_API_DATA_SUCCESS = 'RECEIVE_API_DATA_SUCCESS';
const RECEIVE_API_DATA_FAILURE = 'RECEIVE_API_DATA_FAILURE';

export {RECEIVE_API_DATA_FAILURE, RECEIVE_API_DATA_SUCCESS, REQUEST_API_DATA};
