const REQUEST_API_DATA = 'REQUEST_API_DATA';
const INVOICE_API_DATA_SUCCESS = 'INVOICE_API_DATA_SUCCESS';
const DOMAIN_API_DATA_SUCCESS = 'DOMAIN_API_DATA_SUCCESS';
const SERVICE_API_DATA_SUCCESS = 'SERVICE_API_DATA_SUCCESS';
const LOGIN_API_DATA_SUCCESS = 'LOGIN_API_DATA_SUCCESS';
const REGISTER_API_DATA_SUCCESS = 'REGISTER_API_DATA_SUCCESS';
const API_DATA_FAILURE = 'API_DATA_FAILURE';

export {
  REQUEST_API_DATA,
  INVOICE_API_DATA_SUCCESS,
  DOMAIN_API_DATA_SUCCESS,
  SERVICE_API_DATA_SUCCESS,
  LOGIN_API_DATA_SUCCESS,
  REGISTER_API_DATA_SUCCESS,
  API_DATA_FAILURE,
};
